name: lint

on:
  push:
    branches:
      - main
      - dev*
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: ruff
    steps:
    - uses: actions/checkout@v5
    - name: Install Eigen3 and OpenBLAS
      run: |
        sudo apt-get update
        sudo apt-get install -y libeigen3-dev libopenblas-dev
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install depedencies
      run: uv sync --locked --all-extras --dev
    - name: Run linter
      run: uv run ruff check
